title: CQ_Action Guide
description: A complete guide to using cq_action in Eudemons Online private servers.
markdown: kramdown
theme: minima
# Add this to ensure your includes work:
include:
  - _includes